dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - sudo add-apt-repository ppa:jotik/cmake
  - sudo apt-get update
  - sudo apt-get install cmake
language: 
  c
script: cmake . && make
